SELECT * FROM Parent;
SELECT * FROM Parentaccount;
SELECT * FROM Child;
SELECT * FROM Employee;
SELECT * FROM OfficeLocation;
SELECT * FROM Locations;
SELECT * FROM Attendance;
SELECT * FROM VaccineRecord;
SELECT * FROM VaccineNames;
